security:
  username: ${username}
  password: ${password}

spring:
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import: optional:configserver:http://${username}:${password}@localhost:8888
