spring:
  application:
    name: profile
  profiles:
    active: dev
  config:
    import: optional:configserver:http://${username}:${password}@localhost:8888

security:
  username: ${username}
  password: ${password}